#!/usr/bin/env bash
# Configures the server to listen to port 80, query GET / return Hello world
apt-get update
apt-get install -y nginx

sh -c 'echo "server {
    listen 80;
    server_name localhost;

    location / {
        return 200 \"Hello World!\\n\";
    }
}" > /etc/nginx/sites-available/default'

service nginx restart
