#!/usr/bin/env bash
# Configure Ubuntu to listen at 80, Localhost and redirect
apt-get update
apt-get install -y nginx

sh -c 'echo "server {
    listen 80;
    server_name localhost;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

}" > /etc/nginx/sites-available/default'

service nginx restart
