#!/usr/bin/env bash
# Configure nginx to return a custom header for every response
apt-get update
apt-get install -y nginx

cp /etc/nginx/nginx.conf /etc/nginx/nginx.conf.bak
sed -i "/^http {/a \	add_header X-Served-By $(hostname);" /etc/nginx/nginx.conf

nginx -t
if [ $? -eq 0 ]; then
	service nginx restart
else
	cp /etc/nginx/nginx.conf.bak /etc/nginx/nginx.conf
fi
