#!/usr/bin/env bash
# Configure a server with nginx to listen on port 80 IPV4 IPs
apt-get update
apt-get install -y nginx

cp /etc/nginx/nginx.conf /etc/nginx/nginx.conf.bak

sed -i '/listen/s/80/80 default_server/g' /etc/nginx/nginx.conf

echo "<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
	margin: 0 auto;
	font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>" > /var/www/html/index.html

service nginx restart
