#!/usr/bin/env bash
# Configuring nginx to run on port 80 and listen on all ports
apt-get update
apt-get install -y nginx

echo "server {
        listen 80;
        server_name _;  # Listen on all active IPv4 IPs
        root /var/www/html;     # Set the web root dir

        location / {
                try_files \$uri \$uri/ =404;
        }
}" > /etc/nginx/sites-available/default

# mv /var/www/html/index.nginx-debian.html /var/www/html/index.html

service nginx restart
