#!/usr/bin/env bash
# Configure a server with nginx to listen on port 80 IPV4 IPs
apt-get update
apt-get install -y nginx

cp /etc/nginx/nginx.conf /etc/nginx/nginx.conf.bak

sed -i '/listen/s/80/80 default_server/g' /etc/nginx/nginx.conf

service nginx restart
