#!/usr/bin/env bash
# Creates a file with it's PID, rejects SIGTERM, SIGINT, allows SIGQUIT

echo $$ > /var/run/myscript.pid
trap 'echo "I hate the kill command"; exit 0' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
while true; do
	echo "To infinity and beyond"
	sleep 2
done
