#!/usr/bin/env bash
# Creates a file with it's PID, rejects SIGTERM, SIGINT, allows SIGQUIT

file=/var/run/myscript.pid
echo $$ > $file

quit() {
	rm $file
	exit 0
}

terminate() {
	echo "I hate the kill command"
	quit
}

interrupt() {
	echo "Y U no love me?!"
}

trap 'terminate' SIGTERM
trap 'interrupt' SIGINT
trap 'quit' SIGQUIT

while true; do
	echo "To infinity and beyond"
	sleep 2
done
