#!/usr/bin/env bash
# Tells a story about each user
while IFS=: read -r UNAME PASSW UserID GID UINFO HDIR SCOM; do
	echo "The user $UNAME is part of the $GID gang, lives in $HDIR and rides $SCOM. $UserID's place is protected by the passcode $PASSW, more info about the user here: $UINFO"
done < /etc/passwd
