#!/usr/bin/env bash
# Displays numbers 1 to 20
i=1
max=20
while [ $i -le $max ]; do
	echo $i
	case $i in
		"4")
			echo "bad luck from China"
			;;
		"9")
			echo "bad luck from Japan"
			;;
		"17")
			echo "bad luck from Italy"
			;;
	esac
	i=$((i + 1))
done
