#!/usr/bin/env bash
# Configures ufw to block all incoming except 22, 443, 80
apt-get update
apt-get -y install ufw
ufw default deny incoming
ufw allow 22/tcp
ufw allow 443/tcp
ufw allow 80/tcp
ufw enable
