#!/usr/bin/env bash
# Configures Nginx to run as nginx user
apt-get update
apt-get install -y nginx

useradd -m -s /bin/bash nginx

cp /etc/nginx/nginx.conf /etc/nginx/nginx.conf.bak

sed -i 's/^user .*;/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/80 default_server;/8080 default_server;/g' /etc/nginx/sites-available/default

service nginx restart
