#!/usr/bin/env bash
# Configures Nginx to run as nginx user
apt-get install -y nginx
useradd -m -s /bin/bash nginx
sed -i 's/^user .*;/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/\b80\b/8080/g' /etc/nginx/sites-available/default
service nginx restart
