#!/usr/bin/env bash
# Uses ssh to connect to my server using the private key ~/.ssh/school
server="100.25.119.244"
username="ubuntu"
private_key="~/.ssh/school"

ssh -i "$private_key" "$username"@"$server"
